
### 登录
POST http://{{host}}:{{port}}/system/login
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "username": "admin",
  "password": "8tK2r6Rrfsg9IKTpYqtMug=="
}

> {% client.global.set("auth_token", "Bearer " + response.body.token); %}

###

