### 获取组织树
GET http://{{host}}:{{port}}/system/organizations/search
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

### 添加组织
POST http://{{host}}:{{port}}/system/organizations
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "name": "研发中心",
  "parentId": 0,
  "remark": "研发中心研发核心产品",
  "sort": 100
}

### 编辑组织
PUT http://{{host}}:{{port}}/system/organizations/1377343011159150592
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

{
  "name": "研发中心-1",
  "parentId": 0,
  "remark": "研发中心研发核心产品-1",
  "sort": 100
}

### 删除组织
DELETE http://{{host}}:{{port}}/system/organizations/1377343011159150592
Accept: application/json
Content-Type: application/json;charset=UTF-8
Authorization: {{auth_token}}

###