server:
  port: 8080
#  servlet:
#    context-path: /ekin

spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  application:
    name: ekin
  profiles:
#    include: web, mysql
    active: local


cartisan:
  jwt:
    key: cartisan-jwt
    ttl: 1800000
  info:
    title: Ekin 后台管理系统
    serviceUrl: http://www.cartisan.com
    version: 1.0
    contact:
      name: colin
      url: zhang_colin.github.com
      email: zhang_colin@163.com
  security:
    ignored:
      urls: # 安全路由白名单
        - /
        - /*.html
        - /**/*.html
        - /**/*.css
        - /**/*.js
        - /**/v2/api-docs/**
        - /**/v2/api-docs-ext/**
        - /**/*.png
        - /**/*.ico
        - /swagger-ui.html
        - /swagger-resources/**
        - /swagger/**
        - /webjars/springfox-swagger-ui/**
        - /actuator/**
        - /druid/**
        - /system/login
        - /interface-ui/**
        - /api/**
#        - /admin/register

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always


logging:
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS} %X{request-id} %X{user}] %level - [%thread %logger{30}] - [%replace(%msg){'\n', ''}]%n"
  level:
    root: info

---
spring:
  profiles: local, dev
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID} %10.10X{request-id} %10.10X{user}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: info
    org.apache.http.wire: info
    org.apache.http.headers: info
    # 在日志中打印应用映射的所有请求路径
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    com.cartisan: debug